package ca.hccis.scuba.bo;

import ca.hccis.scuba.entity.Dive;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * AI generated test suite for DiveBO.
 *
 * These tests were generated by AI (Microsoft Copilot) using the project readme
 * requirements and the Dive entity class as input.  They cover every gender,
 * age group and dive scenario value, the depth / time behaviour and the
 * invalid input cases.
 *
 * @author Jonathan Dumaguing (generated with AI)
 * @since 20260930
 */
public class DiveBOAITest {

    private static final double DELTA = 0.0001;

    /**
     * Build a dive with a BSA of exactly 2.0 (180cm x 80kg) so expected values
     * are easy to check.
     */
    private Dive buildDive(String gender, String ageGroup, double depth,
                           double time, String scenario) {
        return new Dive(1, "AI Test", 180.0, 80.0, gender, ageGroup, depth, time, scenario);
    }

    // ---------------- Gender factor ----------------

    @Test
    public void testGenderFactorMale() {
        assertEquals(9.8, DiveBO.getGenderFactor("MALE"), DELTA);
    }

    @Test
    public void testGenderFactorFemale() {
        assertEquals(9.0, DiveBO.getGenderFactor("FEMALE"), DELTA);
    }

    @Test
    public void testGenderFactorInvalid() {
        assertThrows(IllegalArgumentException.class, () -> DiveBO.getGenderFactor("OTHER"));
        assertThrows(IllegalArgumentException.class, () -> DiveBO.getGenderFactor(null));
    }

    // ---------------- Age multiplier ----------------

    @Test
    public void testAgeMultipliers() {
        assertEquals(1.10, DiveBO.getAgeMultiplier("AGE_10S"), DELTA);
        assertEquals(1.00, DiveBO.getAgeMultiplier("AGE_20S"), DELTA);
        assertEquals(0.98, DiveBO.getAgeMultiplier("AGE_30S"), DELTA);
        assertEquals(1.05, DiveBO.getAgeMultiplier("AGE_40S"), DELTA);
        assertEquals(1.15, DiveBO.getAgeMultiplier("AGE_50S_PLUS"), DELTA);
    }

    @Test
    public void testAgeMultiplierInvalid() {
        assertThrows(IllegalArgumentException.class, () -> DiveBO.getAgeMultiplier("AGE_60S"));
        assertThrows(IllegalArgumentException.class, () -> DiveBO.getAgeMultiplier(null));
    }

    // ---------------- Scenario multiplier ----------------

    @Test
    public void testScenarioMultipliers() {
        assertEquals(1.0, DiveBO.getScenarioMultiplier("DRIFT"), DELTA);
        assertEquals(1.25, DiveBO.getScenarioMultiplier("CAVE_WRECK"), DELTA);
        assertEquals(1.5, DiveBO.getScenarioMultiplier("COUNTER_CURRENT"), DELTA);
    }

    @Test
    public void testScenarioMultiplierInvalid() {
        assertThrows(IllegalArgumentException.class, () -> DiveBO.getScenarioMultiplier("NIGHT"));
        assertThrows(IllegalArgumentException.class, () -> DiveBO.getScenarioMultiplier(null));
    }

    // ---------------- Calculate ----------------

    @Test
    public void testCalculateCounterCurrent() {
        //2.0 x 9.8 x 1.0 x 1.5 x 3.0 x 30 / 150 = 17.64
        Dive dive = buildDive("MALE", "AGE_20S", 20.0, 30.0, "COUNTER_CURRENT");
        assertEquals(17.64, DiveBO.calculate(dive), DELTA);
    }

    @Test
    public void testCalculateAtSurface() {
        //Depth 0 means ata = 1.  2.0 x 9.8 x 1.0 x 1.0 x 1.0 x 30 / 150 = 3.92
        Dive dive = buildDive("MALE", "AGE_20S", 0.0, 30.0, "DRIFT");
        assertEquals(3.92, DiveBO.calculate(dive), DELTA);
    }

    @Test
    public void testCalculateZeroTimeIsZero() {
        Dive dive = buildDive("MALE", "AGE_20S", 20.0, 0.0, "DRIFT");
        assertEquals(0.0, DiveBO.calculate(dive), DELTA);
    }

    @Test
    public void testDeeperDiveNeedsBiggerTank() {
        double shallow = DiveBO.calculate(buildDive("MALE", "AGE_20S", 10.0, 30.0, "DRIFT"));
        double deep = DiveBO.calculate(buildDive("MALE", "AGE_20S", 30.0, 30.0, "DRIFT"));
        assertTrue(deep > shallow, "Deeper dive should need a bigger tank");
    }

    @Test
    public void testLongerDiveNeedsBiggerTank() {
        double shortDive = DiveBO.calculate(buildDive("MALE", "AGE_20S", 20.0, 20.0, "DRIFT"));
        double longDive = DiveBO.calculate(buildDive("MALE", "AGE_20S", 20.0, 40.0, "DRIFT"));
        assertEquals(shortDive * 2, longDive, DELTA);
    }

    @Test
    public void testMaleNeedsMoreAirThanFemale() {
        double male = DiveBO.calculate(buildDive("MALE", "AGE_20S", 20.0, 30.0, "DRIFT"));
        double female = DiveBO.calculate(buildDive("FEMALE", "AGE_20S", 20.0, 30.0, "DRIFT"));
        assertTrue(male > female, "Male factor 9.8 is higher than female factor 9.0");
    }

    @Test
    public void testCalculateNegativeWeightThrows() {
        Dive dive = new Dive(1, "AI Test", 180.0, -5.0, "MALE", "AGE_20S", 20.0, 30.0, "DRIFT");
        assertThrows(IllegalArgumentException.class, () -> DiveBO.calculate(dive));
    }

    @Test
    public void testCalculateNegativeDepthThrows() {
        Dive dive = buildDive("MALE", "AGE_20S", -1.0, 30.0, "DRIFT");
        assertThrows(IllegalArgumentException.class, () -> DiveBO.calculate(dive));
    }

    @Test
    public void testCalculateNegativeTimeThrows() {
        Dive dive = buildDive("MALE", "AGE_20S", 20.0, -1.0, "DRIFT");
        assertThrows(IllegalArgumentException.class, () -> DiveBO.calculate(dive));
    }

    @Test
    public void testCalculateInvalidScenarioThrows() {
        Dive dive = buildDive("MALE", "AGE_20S", 20.0, 30.0, "NIGHT");
        assertThrows(IllegalArgumentException.class, () -> DiveBO.calculate(dive));
    }
}
