package ca.hccis.files;

import ca.hccis.files.entity.Dive;
import ca.hccis.util.CisUtility;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;

/**
 * Controls the overall flow of the Scuba Dive Air Consumption and Tank Planner
 * console application.
 *
 * @author Jonathan Dumaguing
 * @since 20260923
 */
public class Controller {

    public static final String ADD = "A";
    public static final String VIEW = "V";
    public static final String EDIT = "E";
    public static final String EXIT = "X";

    public static final String MENU = "A) Add" + System.lineSeparator()
            + "V) View" + System.lineSeparator()
            + "E) Edit" + System.lineSeparator()
            + EXIT + ") eXit"
            + System.lineSeparator();

    public static final String MESSAGE_ERROR = "Error";
    public static final String MESSAGE_EXIT = "Goodbye";
    public static final String MESSAGE_SUCCESS = "Success";

    private static HashMap<Integer, Dive> diveMap = new HashMap();
    private static Gson gson = new Gson();

    public static final String FOLDER_NAME = "c:\\cis2232";
    public static final String FILE_NAME = "data_dumaguing_jonathan.json";
    public static final String PATH_NAME = FOLDER_NAME + "\\" + FILE_NAME;

    public static void main(String[] args) {

        initialize();

        String menuOption;
        do {
            menuOption = CisUtility.getInputString(MENU).trim().toUpperCase();

            switch (menuOption) {
                case EXIT:
                    System.out.println(MESSAGE_EXIT);
                    break;
                case ADD:
                    add();
                    break;
                case VIEW:
                    viewAll();
                    break;
                case EDIT:
                    edit();
                    break;
                default:
                    System.out.println(MESSAGE_ERROR);
                    break;
            }
        } while (!menuOption.equals(EXIT));
    }

    /**
     * Processing for menu option A.  The diver name is asked first so the duplicate
     * check happens before the user types in all the other fields.  The diveId is
     * generated by the program, the user does not enter it.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void add() {

        readAll();

        System.out.println("--Add Dive Plan--");
        String diverName = getValidDiverName();

        //Check if this diver already has a plan.  The name check ignores upper/lower case.
        Dive existingDive = findByDiverName(diverName);
        int diveId;

        if (existingDive != null) {
            System.out.println("Warning: dive plan already exists for this diver!");
            System.out.println(existingDive.toString());

            boolean overwrite = CisUtility.getInputBoolean("Overwrite this dive plan?");
            if (!overwrite) {
                System.out.println("Add cancelled.");
                return;
            }
            //Keep the same diveId so the old plan is replaced instead of duplicated.
            diveId = existingDive.getDiveId();
        } else {
            diveId = getNextDiveId();
        }

        Dive newDive = new Dive();
        newDive.setDiveId(diveId);
        newDive.setDiverName(diverName);
        newDive.getInformation();

        diveMap.put(newDive.getDiveId(), newDive);
        writeAll();
        System.out.println(MESSAGE_SUCCESS + " - dive plan saved with dive id " + diveId + ".");
    }

    /**
     * Processing for menu option E.  The user picks the dive plan using the diveId
     * which they can see from the View option.
     *
     * The same getInformation() method used by add is called here so the prompts
     * and the validation only need to be written in one place.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void edit() {

        readAll();

        System.out.println("--Edit Dive Plan--");
        int diveId = getValidDiveId();

        Dive editingDive = diveMap.get(diveId);

        //Handle the situation where the diveId was not found.
        if (editingDive == null) {
            System.out.println(MESSAGE_ERROR + " - No dive plan found with dive id " + diveId + ".");
            return;
        }

        System.out.println("Current values:");
        System.out.println(editingDive.toString());
        System.out.println("Please enter the new values.");

        //The diver name is asked here so we can make sure it is not being changed
        //to a name which already belongs to a different dive plan.
        String diverName = getValidDiverName();
        Dive nameOwner = findByDiverName(diverName);

        if (nameOwner != null && nameOwner.getDiveId() != editingDive.getDiveId()) {
            System.out.println(MESSAGE_ERROR + " - another dive plan already uses this diver name.");
            System.out.println("Edit cancelled.");
            return;
        }

        editingDive.setDiverName(diverName);
        editingDive.getInformation();

        diveMap.put(editingDive.getDiveId(), editingDive);

        writeAll();
        System.out.println(MESSAGE_SUCCESS);
    }

    /**
     * Processing for menu option V.  Shows the latest from the file, not just what
     * is currently in the map.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void viewAll() {

        readAll();

        if (diveMap.isEmpty()) {
            System.out.println("There are no dive plans to display.");
            return;
        }

        System.out.println("--All Dive Plans (" + diveMap.size() + ")--");
        for (Dive current : diveMap.values()) {
            System.out.println(current.toString());
        }
    }

    /**
     * Keep asking until the user enters a diver name which is not blank.
     *
     * @return A valid diver name
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static String getValidDiverName() {
        String diverName = CisUtility.getInputString("Diver Name").trim();
        while (diverName.isEmpty()) {
            System.out.println("Diver name cannot be blank.");
            diverName = CisUtility.getInputString("Diver Name").trim();
        }
        return diverName;
    }

    /**
     * Keep asking until the user enters a whole number for the dive id.  Letters
     * are rejected instead of crashing the program.
     *
     * @return A valid dive id entered by the user
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static int getValidDiveId() {
        while (true) {
            String entered = CisUtility.getInputString("Dive ID").trim();
            try {
                return Integer.parseInt(entered);
            } catch (NumberFormatException e) {
                System.out.println("'" + entered + "' is not a valid dive id.  Please try again.");
            }
        }
    }

    /**
     * Find a dive plan using the diver name.  The comparison ignores upper and lower
     * case so "Jonathan Dumaguing" and "jonathan dumaguing" are treated as the same
     * diver.
     *
     * @param diverName Name of the diver being looked for
     * @return The matching dive plan, or null when the diver was not found
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static Dive findByDiverName(String diverName) {
        for (Dive current : diveMap.values()) {
            if (current.getDiverName() != null
                    && current.getDiverName().trim().equalsIgnoreCase(diverName.trim())) {
                return current;
            }
        }
        return null;
    }

    /**
     * Determine the next diveId to use for a new dive plan.
     *
     * @return The highest diveId currently in use plus one
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static int getNextDiveId() {
        int maxDiveId = 1000;
        for (Dive current : diveMap.values()) {
            if (current.getDiveId() > maxDiveId) {
                maxDiveId = current.getDiveId();
            }
        }
        return maxDiveId + 1;
    }

    /**
     * Write each dive plan in the map to the file, one json string per line.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void writeAll() {
        try {
            FileWriter writer = new FileWriter(PATH_NAME, false);
            for (Dive current : diveMap.values()) {
                writer.append(gson.toJson(current));
                writer.append(System.lineSeparator());
            }
            System.out.println("Successfully written JSON string to file.");
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Read each line from the file and load the dive plans into the map.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void readAll() {
        try {
            BufferedReader reader = new BufferedReader(new FileReader(PATH_NAME));
            String line = reader.readLine();
            while (line != null) {
                if (!line.trim().isEmpty()) {
                    Dive diveFromJson = gson.fromJson(line, Dive.class);
                    diveMap.put(diveFromJson.getDiveId(), diveFromJson);
                }
                line = reader.readLine();
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates the cis2232 folder when it does not already exist.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void createFolderIfMissing() throws IOException {
        Path folder = Paths.get(FOLDER_NAME);
        if (!Files.exists(folder)) {
            Files.createDirectories(folder);
            System.out.println("Created folder " + FOLDER_NAME);
        }
    }

    /**
     * Make sure the folder exists, then load the data saved the last time the
     * program was run.  If there is no file yet, create it with sample dive plans.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public static void initialize() {
        try {
            createFolderIfMissing();
        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        Path path = Paths.get(PATH_NAME);

        if (Files.exists(path)) {
            System.out.println("Dive plans exist.");
            readAll();
        } else {
            Dive dive1 = new Dive(1001, "Jonathan Dumaguing", 170.0, 72.0,
                    "MALE", "AGE_30S", 18.0, 40.0, "DRIFT");
            Dive dive2 = new Dive(1002, "Sean Doyle", 180.0, 85.0,
                    "MALE", "AGE_20S", 30.0, 25.0, "CAVE_WRECK");
            Dive dive3 = new Dive(1003, "Jake Murphy", 175.0, 78.0,
                    "MALE", "AGE_40S", 12.0, 50.0, "COUNTER_CURRENT");
            Dive dive4 = new Dive(1004, "Maria Santos", 160.0, 55.0,
                    "FEMALE", "AGE_20S", 15.0, 45.0, "DRIFT");
            Dive dive5 = new Dive(1005, "Anna Reid", 165.0, 62.0,
                    "FEMALE", "AGE_50S_PLUS", 22.0, 30.0, "CAVE_WRECK");

            diveMap.put(dive1.getDiveId(), dive1);
            diveMap.put(dive2.getDiveId(), dive2);
            diveMap.put(dive3.getDiveId(), dive3);
            diveMap.put(dive4.getDiveId(), dive4);
            diveMap.put(dive5.getDiveId(), dive5);

            writeAll();
        }
    }
}
