package ca.hccis.files.entity;

import ca.hccis.util.CisUtility;

/**
 * Represents a single scuba dive plan entry for the Scuba Dive Air Consumption
 * and Tank Planner.
 *
 * The diveId is auto generated by the Controller, it is not entered by the user.
 *
 * NOTE: The SAC / air volume / tank size calculations are NOT coded here.
 * Those will be added in the unit testing assignment using TDD.
 *
 * @author Jonathan Dumaguing
 * @since 20260923
 */
public class Dive {

    private int diveId;
    private String diverName;
    private double heightCm;
    private double weightKg;
    private String gender;          // MALE / FEMALE
    private String ageGroup;        // AGE_10S, AGE_20S, AGE_30S, AGE_40S, AGE_50S_PLUS
    private double targetDepthMeters;
    private double plannedTimeMinutes;
    private String diveScenario;    // DRIFT, CAVE_WRECK, COUNTER_CURRENT

    public Dive() {
    }

    public Dive(int diveId, String diverName, double heightCm, double weightKg,
                String gender, String ageGroup, double targetDepthMeters,
                double plannedTimeMinutes, String diveScenario) {
        this.diveId = diveId;
        this.diverName = diverName;
        this.heightCm = heightCm;
        this.weightKg = weightKg;
        this.gender = gender;
        this.ageGroup = ageGroup;
        this.targetDepthMeters = targetDepthMeters;
        this.plannedTimeMinutes = plannedTimeMinutes;
        this.diveScenario = diveScenario;
    }

    /**
     * Gather the rest of the information for a new dive plan from the console.
     * The diver name is already collected by the Controller so the duplicate
     * check can happen before the user types everything else.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public void getInformation() {
        heightCm = CisUtility.getInputDouble("Height (cm)");
        weightKg = CisUtility.getInputDouble("Weight (kg)");
        gender = getGenderFromUser();
        ageGroup = getAgeGroupFromUser();
        targetDepthMeters = CisUtility.getInputDouble("Target Depth (meters)");
        plannedTimeMinutes = CisUtility.getInputDouble("Planned Bottom Time (minutes)");
        diveScenario = getScenarioFromUser();
    }

    /**
     * Allow the user to change the details of an existing dive plan.  The diveId
     * is the key so it is not editable here.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public void edit() {
        diverName = CisUtility.getInputString("Diver Name [" + diverName + "]");
        heightCm = CisUtility.getInputDouble("Height in cm [" + heightCm + "]");
        weightKg = CisUtility.getInputDouble("Weight in kg [" + weightKg + "]");
        gender = getGenderFromUser();
        ageGroup = getAgeGroupFromUser();
        targetDepthMeters = CisUtility.getInputDouble("Target Depth in meters [" + targetDepthMeters + "]");
        plannedTimeMinutes = CisUtility.getInputDouble("Planned Time in minutes [" + plannedTimeMinutes + "]");
        diveScenario = getScenarioFromUser();
    }

    /**
     * Keep asking until the user enters a valid gender.
     */
    private String getGenderFromUser() {
        String value = CisUtility.getInputString("Gender (MALE/FEMALE)").trim().toUpperCase();
        while (!value.equals("MALE") && !value.equals("FEMALE")) {
            System.out.println("Invalid gender.  Please enter MALE or FEMALE.");
            value = CisUtility.getInputString("Gender (MALE/FEMALE)").trim().toUpperCase();
        }
        return value;
    }

    /**
     * Keep asking until the user enters a valid age group.
     */
    private String getAgeGroupFromUser() {
        String prompt = "Age Group (AGE_10S, AGE_20S, AGE_30S, AGE_40S, AGE_50S_PLUS)";
        String value = CisUtility.getInputString(prompt).trim().toUpperCase();
        while (!value.equals("AGE_10S") && !value.equals("AGE_20S") && !value.equals("AGE_30S")
                && !value.equals("AGE_40S") && !value.equals("AGE_50S_PLUS")) {
            System.out.println("Invalid age group.");
            value = CisUtility.getInputString(prompt).trim().toUpperCase();
        }
        return value;
    }

    /**
     * Keep asking until the user enters a valid dive scenario.
     */
    private String getScenarioFromUser() {
        String prompt = "Dive Scenario (DRIFT, CAVE_WRECK, COUNTER_CURRENT)";
        String value = CisUtility.getInputString(prompt).trim().toUpperCase();
        while (!value.equals("DRIFT") && !value.equals("CAVE_WRECK") && !value.equals("COUNTER_CURRENT")) {
            System.out.println("Invalid scenario.");
            value = CisUtility.getInputString(prompt).trim().toUpperCase();
        }
        return value;
    }

    public int getDiveId() {
        return diveId;
    }

    public void setDiveId(int diveId) {
        this.diveId = diveId;
    }

    public String getDiverName() {
        return diverName;
    }

    public void setDiverName(String diverName) {
        this.diverName = diverName;
    }

    public double getHeightCm() {
        return heightCm;
    }

    public void setHeightCm(double heightCm) {
        this.heightCm = heightCm;
    }

    public double getWeightKg() {
        return weightKg;
    }

    public void setWeightKg(double weightKg) {
        this.weightKg = weightKg;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAgeGroup() {
        return ageGroup;
    }

    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    public double getTargetDepthMeters() {
        return targetDepthMeters;
    }

    public void setTargetDepthMeters(double targetDepthMeters) {
        this.targetDepthMeters = targetDepthMeters;
    }

    public double getPlannedTimeMinutes() {
        return plannedTimeMinutes;
    }

    public void setPlannedTimeMinutes(double plannedTimeMinutes) {
        this.plannedTimeMinutes = plannedTimeMinutes;
    }

    public String getDiveScenario() {
        return diveScenario;
    }

    public void setDiveScenario(String diveScenario) {
        this.diveScenario = diveScenario;
    }

    @Override
    public String toString() {
        return String.format(
                "Dive: diveId=%d, diverName='%s', height=%.1fcm, weight=%.1fkg, gender='%s', "
                        + "ageGroup='%s', depth=%.1fm, time=%.1fmin, scenario='%s'",
                diveId, diverName, heightCm, weightKg, gender, ageGroup,
                targetDepthMeters, plannedTimeMinutes, diveScenario);
    }
}
