package ca.hccis.files.entity;

import ca.hccis.util.CisUtility;

/**
 * Represents a single scuba dive plan entry for the Scuba Dive Air Consumption
 * and Tank Planner.
 *
 * The diveId is auto generated by the Controller, it is not entered by the user.
 *
 * @author Jonathan Dumaguing
 * @since 20260923
 */
public class Dive {

    //Validation ranges for the numeric fields.
    public static final double HEIGHT_MIN = 100.0;
    public static final double HEIGHT_MAX = 250.0;
    public static final double WEIGHT_MIN = 30.0;
    public static final double WEIGHT_MAX = 250.0;
    public static final double DEPTH_MIN = 1.0;
    public static final double DEPTH_MAX = 40.0;
    public static final double TIME_MIN = 1.0;
    public static final double TIME_MAX = 240.0;

    private int diveId;
    private String diverName;
    private double heightCm;
    private double weightKg;
    private String gender;          // MALE / FEMALE
    private String ageGroup;        // AGE_10S, AGE_20S, AGE_30S, AGE_40S, AGE_50S_PLUS
    private double targetDepthMeters;
    private double plannedTimeMinutes;
    private String diveScenario;    // DRIFT, CAVE_WRECK, COUNTER_CURRENT

    public Dive() {
    }

    public Dive(int diveId, String diverName, double heightCm, double weightKg,
                String gender, String ageGroup, double targetDepthMeters,
                double plannedTimeMinutes, String diveScenario) {
        this.diveId = diveId;
        this.diverName = diverName;
        this.heightCm = heightCm;
        this.weightKg = weightKg;
        this.gender = gender;
        this.ageGroup = ageGroup;
        this.targetDepthMeters = targetDepthMeters;
        this.plannedTimeMinutes = plannedTimeMinutes;
        this.diveScenario = diveScenario;
    }

    /**
     * Gather the dive plan details from the console.  This is used by both the add
     * and the edit options so the prompts are only written in one place.
     *
     * The diver name is not asked here.  For an add it is collected by the
     * Controller before this method is called so the duplicate name check can
     * happen first, and for an edit the Controller asks for it separately.
     *
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    public void getInformation() {
        heightCm = getValidDouble("Height (cm)", HEIGHT_MIN, HEIGHT_MAX);
        weightKg = getValidDouble("Weight (kg)", WEIGHT_MIN, WEIGHT_MAX);
        gender = getGenderFromUser();
        ageGroup = getAgeGroupFromUser();
        targetDepthMeters = getValidDouble("Target Depth (meters)", DEPTH_MIN, DEPTH_MAX);
        plannedTimeMinutes = getValidDouble("Planned Bottom Time (minutes)", TIME_MIN, TIME_MAX);
        diveScenario = getScenarioFromUser();
    }

    /**
     * Keep asking until the user enters a number which is inside the allowed range.
     * Letters or blank entries are rejected instead of crashing the program.
     *
     * @param prompt Prompt for the user
     * @param min Smallest value accepted
     * @param max Largest value accepted
     * @return A valid double entered by the user
     * @author Jonathan Dumaguing
     * @since 20260923
     */
    private double getValidDouble(String prompt, double min, double max) {

        String fullPrompt = prompt + " (" + min + " to " + max + ")";

        while (true) {
            String entered = CisUtility.getInputString(fullPrompt).trim();

            try {
                double value = Double.parseDouble(entered);

                if (value < min || value > max) {
                    System.out.println("Value must be between " + min + " and " + max + ".");
                    continue;
                }
                return value;

            } catch (NumberFormatException e) {
                System.out.println("'" + entered + "' is not a valid number.  Please try again.");
            }
        }
    }

    /**
     * Keep asking until the user enters a valid gender.
     */
    private String getGenderFromUser() {
        String value = CisUtility.getInputString("Gender (MALE/FEMALE)").trim().toUpperCase();
        while (!value.equals("MALE") && !value.equals("FEMALE")) {
            System.out.println("Invalid gender.  Please enter MALE or FEMALE.");
            value = CisUtility.getInputString("Gender (MALE/FEMALE)").trim().toUpperCase();
        }
        return value;
    }

    /**
     * Keep asking until the user enters a valid age group.
     */
    private String getAgeGroupFromUser() {
        String prompt = "Age Group (AGE_10S, AGE_20S, AGE_30S, AGE_40S, AGE_50S_PLUS)";
        String value = CisUtility.getInputString(prompt).trim().toUpperCase();
        while (!value.equals("AGE_10S") && !value.equals("AGE_20S") && !value.equals("AGE_30S")
                && !value.equals("AGE_40S") && !value.equals("AGE_50S_PLUS")) {
            System.out.println("Invalid age group.");
            value = CisUtility.getInputString(prompt).trim().toUpperCase();
        }
        return value;
    }

    /**
     * Keep asking until the user enters a valid dive scenario.
     */
    private String getScenarioFromUser() {
        String prompt = "Dive Scenario (DRIFT, CAVE_WRECK, COUNTER_CURRENT)";
        String value = CisUtility.getInputString(prompt).trim().toUpperCase();
        while (!value.equals("DRIFT") && !value.equals("CAVE_WRECK") && !value.equals("COUNTER_CURRENT")) {
            System.out.println("Invalid scenario.");
            value = CisUtility.getInputString(prompt).trim().toUpperCase();
        }
        return value;
    }

    public int getDiveId() {
        return diveId;
    }

    public void setDiveId(int diveId) {
        this.diveId = diveId;
    }

    public String getDiverName() {
        return diverName;
    }

    public void setDiverName(String diverName) {
        this.diverName = diverName;
    }

    public double getHeightCm() {
        return heightCm;
    }

    public void setHeightCm(double heightCm) {
        this.heightCm = heightCm;
    }

    public double getWeightKg() {
        return weightKg;
    }

    public void setWeightKg(double weightKg) {
        this.weightKg = weightKg;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAgeGroup() {
        return ageGroup;
    }

    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    public double getTargetDepthMeters() {
        return targetDepthMeters;
    }

    public void setTargetDepthMeters(double targetDepthMeters) {
        this.targetDepthMeters = targetDepthMeters;
    }

    public double getPlannedTimeMinutes() {
        return plannedTimeMinutes;
    }

    public void setPlannedTimeMinutes(double plannedTimeMinutes) {
        this.plannedTimeMinutes = plannedTimeMinutes;
    }

    public String getDiveScenario() {
        return diveScenario;
    }

    public void setDiveScenario(String diveScenario) {
        this.diveScenario = diveScenario;
    }

    @Override
    public String toString() {
        return String.format(
                "Dive: diveId=%d, diverName='%s', height=%.1fcm, weight=%.1fkg, gender='%s', "
                        + "ageGroup='%s', depth=%.1fm, time=%.1fmin, scenario='%s'",
                diveId, diverName, heightCm, weightKg, gender, ageGroup,
                targetDepthMeters, plannedTimeMinutes, diveScenario);
    }
}
